### ISSUE TITLE
Problem uninstalling Network Scanner

### ISSUE THREAD

**Issue by flemmingkok** [parvez/network_scanner#24]
Hi, tried out the Network Scanner integration, but want to uinstall, sorry, and has this error now - any hints for a semi newbie to get rid of the errors? Searched all .yaml files for Network Scanner references, no luck. Deleted integration, but error keeps coming up.

Home Assistant Core
2024-10-24 09:16:07.475 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Integration ‘network_scanner’ not found.

2024-10-24 09:16:07.975 ERROR (MainThread) [homeassistant.setup] Setup failed for ‘network_scanner’: Integration not found.

homeassistant.loader.IntegrationNotFound: Integration ‘network_scanner’ not found.

2024-10-24 09:23:38.559 ERROR (MainThread) [homeassistant.helpers.dispatcher] Exception in async_forward_config_entry_changes when dispatching ‘config_entry_changed’: (<ConfigEntryChange.UPDATED: ‘updated’>, )

homeassistant.loader.IntegrationNotLoaded: Integration ‘network_scanner’ not loaded.

homeassistant.loader.IntegrationNotFound: Integration ‘network_scanner’ not found.

homeassistant.loader.IntegrationNotFound: Integration ‘network_scanner’ not found.

homeassistant.loader.IntegrationNotFound: Integration ‘network_scanner’ not found.

**Comment by vb7445** [comment]
I am also having a problem uninstalling network scanner. I deleted it from HACS and removed the configuration from the yaml, restarted and rebooted HA.Now I keep getting these errors in the log.

> Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:542
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:29:38 AM (3 occurrences)
Last logged: 9:50:52 AM
[281472778223840] Error handling message: Unknown error (unknown_error)  from 192.168.1.108 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edg/136.0.0.0)
[281472402891424] Error handling message: Unknown error (unknown_error) Philip Dommer from 192.168.1.108 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edg/136.0.0.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 542, in handle_manifest_list
    raise int_or_exc
homeassistant.loader.IntegrationNotFound: Integration 'network_scanner' not found.
